import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import { ThemeSwitcher } from "./components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <div className="flex flex-col items-center justify-center m-20">
                        <h1 className="text-4xl font-bold">员工管理系统</h1>
                        <div className="w-9/12 m-10 border-4 h-full p-4">
                            {children}
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
